# This file was generated by GoReleaser. DO NOT EDIT.
cask "o7k" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "befa9c9a62f87a50dc4f452fc7ca57a0949cb6799a6def72649670aaf74e4da0"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ef35980e1ccdf51e50ec11b13413e36d36f9504375816c37fd5f576ed0a59d82"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f2b450a044d665655287eb0ac7ea0ea1db106b11f78870e3321c718ac4646633"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c154845f26d69590a1c4611781cab5830bb49b38652506e96fad3e60cc094a91"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_linux_amd64.tar.gz"
    end
  end

  name "o7k"
  desc "Terminal UI for OpenStack"
  homepage "https://github.com/akyriako/o7k"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "o7k"

  # No zap stanza required
end
