# This file was generated by GoReleaser. DO NOT EDIT.
cask "o7k" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "a413f6182441caef40817f54c1856d924d6c67606c8b27269ac49d5f92c934c8"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "116b260b1dcdd07320683e56abfcbf3db21e321ede1ee86141d76c858109d9a2"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7c13d6efff0d29d4efc23f89b586667e7ac197cc281bc268632f833eddca503e"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2473b076d4f55304935f85be0c0289710ca7c243ea6b01e16ae4bf2e072e3f80"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_linux_amd64.tar.gz"
    end
  end

  name "o7k"
  desc "Terminal UI for OpenStack"
  homepage "https://github.com/akyriako/o7k"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "o7k"

  # No zap stanza required
end
