# This file was generated by GoReleaser. DO NOT EDIT.
cask "o7k" do
  version "0.8.3"

  on_macos do
    on_arm do
      sha256 "638bbf25a376f2ff8956999ef4cdc25fdc0ed204048aaacc7d7258a9e2430b18"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d039b8e7ba333479e2b024d08947c62f83bfe81bf493314caf0b92fa1304677e"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb0a8a1fe1e2e0642cd0068cb4df9f967462eb13396138bca7ba6d852919d3b2"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b55d7c002acd88f0900a53c47521555992dabbe2681875f3b6b1d1f9cbf3b800"
      url "https://github.com/akyriako/o7k/releases/download/v#{version}/o7k_#{version}_linux_amd64.tar.gz"
    end
  end

  name "o7k"
  desc "Terminal UI for OpenStack"
  homepage "https://github.com/akyriako/o7k"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "o7k"

  # No zap stanza required
end
